# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5  # Ruff version.
    hooks:
      - id: ruff  # Run the linter.
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format  # Run the formatter.
        types_or: [python, pyi]
