name: ccc-rapid
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - rapids=24.08
  - cuda-version>=12.0,<=12.5
  - cupy=13.*
  - numba=0.6.*
  - python=3.11
  - pytest=8.*
  - pybind11=2.*
