name: clustermatch_gene_expr
channels:
  - conda-forge
dependencies:
  - ipython=7.*
  - ipywidgets
  - jupyterlab=3.1.*
  - jupytext=1.11.*
  - matplotlib=3.4.*
  - numpy=1.21.*
  - openpyxl=3.0.*
  - pandas=1.3.*
  - papermill=2.3.*
  - pip
  - pytest=6.*
  - python=3.9.*
  - pyyaml=5.4.*
  - requests=2.*
  - r-base=4.1.*
  - r-devtools
  - r-essentials
  - r-reticulate=1.*
  - r-svglite=2.*
  - rpy2=3.4.*
  - scikit-learn=0.24.*
  - scipy=1.7.*
  - seaborn=0.11.*
  - tabulate=0.8.*
  - tqdm=4.*

