name: clustermatch_gene_expr
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - ipywidgets
  - jupyterlab
  - jupytext
  - matplotlib
  - minepy
  - numba
  - numpy
  - openpyxl
  - pandas
  - papermill
  - pip
  - pytables
  - pytest
  - python=3.9.*
  - pyyaml
  - requests
  - r-base
  - r-devtools
  - r-essentials
  - r-reticulate
  - r-svglite
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - svgutils
  - tabulate
  - tqdm
  - upsetplot

