# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: all,-execution,-papermill,-trusted
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.11.5
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown] tags=[]
# # Description

# %% [markdown] tags=[]
# Tests whether the distribution of pvalues generated by CCC is the expected one (uniform).

# %% [markdown] tags=[]
# # Modules loading

# %% tags=[]
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

from ccc.coef import ccc

# %% [markdown] tags=[]
# # Generate random data

# %% tags=[]
data = np.random.rand(100, 1000)

# %% tags=[]
data.shape

# %% [markdown] tags=[]
# # Run CCC

# %% tags=[]
res = ccc(data, n_jobs=20, pvalue_n_perms=1000, use_ari_numba=True)

# %% [markdown] tags=[]
# # Plots

# %% tags=[]
plt.hist(res[1], bins=10, edgecolor="k")  # Adjust the number of bins as needed
plt.title("Distribution of Values")
plt.xlabel("Value")
plt.ylabel("Frequency")

# %% tags=[]
sns.histplot(res[1], kde=True, color="blue")
plt.title("Distribution of Values")
plt.xlabel("Value")
plt.ylabel("Density")

# %% [markdown] tags=[]
# # KS

# %% tags=[]
stats.ks_1samp(res[1], stats.uniform.cdf)

# %% tags=[]
